# Generated by Django 4.2.7 on 2026-02-27 22:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Settings',
            },
        ),
        migrations.CreateModel(
            name='ConversionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('offer_id', models.CharField(max_length=50)),
                ('offer_name', models.CharField(max_length=200)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user_ip', models.GenericIPAddressField()),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('flagged', 'Flagged for Review')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_id'], name='insights_co_trackin_a6c2da_idx'), models.Index(fields=['status', 'created_at'], name='insights_co_status_0e0de1_idx'), models.Index(fields=['user_ip'], name='insights_co_user_ip_bbf87d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CachedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('offer_link', models.URLField(max_length=500)),
                ('offer_type', models.CharField(max_length=50)),
                ('countries', models.CharField(help_text='Comma-separated country codes', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Review Queue'), ('live', 'Live on Website'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to top of listings')),
                ('display_order', models.IntegerField(default=0, help_text='Manual ranking (lower number = higher priority)')),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', 'display_order', '-payout'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='insights_ca_status_edc81a_idx'), models.Index(fields=['payout'], name='insights_ca_payout_c31c73_idx')],
            },
        ),
    ]
