# Generated by Django 4.2.7 on 2026-02-27 23:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedoffer',
            name='clicks',
            field=models.IntegerField(default=0, help_text='Number of clicks'),
        ),
        migrations.AddField(
            model_name='cachedoffer',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Conversion rate percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='cachedoffer',
            name='date_added',
            field=models.DateField(blank=True, help_text='Date offer was added', null=True),
        ),
        migrations.AddField(
            model_name='cachedoffer',
            name='leads',
            field=models.IntegerField(default=0, help_text='Number of leads/conversions'),
        ),
        migrations.AddField(
            model_name='cachedoffer',
            name='net_epc',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Net Earnings Per Click', max_digits=10),
        ),
        migrations.AddField(
            model_name='cachedoffer',
            name='offer_category',
            field=models.CharField(blank=True, help_text='Main category (e.g., Mobile Install, Email/Zip Submit)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cachedoffer',
            name='offer_image',
            field=models.URLField(blank=True, help_text='Thumbnail/offer image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cachedoffer',
            name='performance_percentage',
            field=models.IntegerField(default=0, help_text='Performance score/percentage'),
        ),
        migrations.AddField(
            model_name='cachedoffer',
            name='required_device',
            field=models.CharField(blank=True, help_text='Required device (e.g., Android, iOS, Desktop)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='cachedoffer',
            index=models.Index(fields=['countries'], name='insights_ca_countri_6cc909_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedoffer',
            index=models.Index(fields=['offer_category'], name='insights_ca_offer_c_a9cc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedoffer',
            index=models.Index(fields=['required_device'], name='insights_ca_require_825c7c_idx'),
        ),
    ]
